modLoader = "javafml" #mandatory
loaderVersion = "${forge_loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "${license}" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/MrNavaStar/ProtoWeaver/issues"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
logoFile = "${mod_id}.png" #optional
authors = "${mod_author}" #optional
description = '''${description}''' #mandatory (Supports multiline text)